version: 2
updates:
- package-ecosystem: maven
  directory: /
  schedule:
    interval: monthly
  open-pull-requests-limit: 10
  target-branch: master
#  ignore:
#    - dependency-name: "xxx"
#- package-ecosystem: github-actions
#  directory: /
#  schedule:
#    interval: monthly
